### ISSUE TITLE
crypto_encrypt and mcbits

### ISSUE THREAD

**Issue by Nouri-Alnahawi** [cyph/mceliece.js#1]
Dear Ryan,

I've stumbled upon your repo while searching for some examples of using mcbits, because I can't build the library. Compilation fails with the following error:

```
mcbits/operations.c:1:28: fatal error: crypto_encrypt.h: No such file or directory
compilation terminated.
```

Somehow I cannot find any guides or readme regarding the usage of mcbits, and could't find the mentioned header file.

Would you please briefly explain how you got mcbits to work, and where you found the missing header file?

Cheers
Nouri

**Comment by buu700** [comment]
Hey @Nouri-Alnahawi, sorry I missed this! Are you still having trouble getting it to build?

I think I might have written crypto_encrypt.h myself or copied/adapted it from libsodium, and then if you look at Makefile you can see that I'm also pulling in code from [SUPERCOP](https://bench.cr.yp.to/supercop.html) that it depends on.

**Comment by Nouri-Alnahawi** [comment]
No Problem, thanks anyways!
